# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.define "craneserver", autostart: false do |craneserver|
        craneserver.vm.box = "centos/7"
        craneserver.vm.hostname = "crane.pulpcluster"
        craneserver.vm.network "private_network", ip: "192.168.33.53"
	craneserver.vm.synced_folder "../artifacts", "/artifacts"
        craneserver.vm.provision :shell, inline: <<-SHELL
                chmod +x /artifacts/scripts/prereq.sh;
                /artifacts/scripts/prereq.sh;
                chmod +x /artifacts/scripts/setupcrane.sh;
                /artifacts/scripts/setupcrane.sh
                cat /artifacts/hosts >> /etc/hosts;
        SHELL
  end  	
end
